### ISSUE TITLE
Are there any articles to explain these patterns in this project?

### ISSUE THREAD

**Issue by ShannonChenCHN** [marty-suzuki/iOSDesignPatternSamples#7]
This is a cool project! 

If there are some articles to explain the patterns used in this projects and how you think of these pattens, that would be awesome.

Anyway, Thanks for sharing!

**Comment by marty-suzuki** [comment]
Hi, @ShannonChenCHN 

I talked about iOS design patterns in [iOSDC Japan 2017](https://iosdc.jp/2017/node/1396).
In that talk, I used this project.
This is presentation slides.
https://speakerdeck.com/martysuzuki/mvc-nil-mvp-nil-mvvm-nil-fluxfalseshi-zhuang-falsewei-iwobi-jiao-sitemiru

**Comment by ShannonChenCHN** [comment]
@marty-suzuki  Thanks a lot! 😀

**Comment by marty-suzuki** [comment]
Hi, @ShannonChenCHN  !
This is additional article that written in Japanese.
https://qiita.com/marty-suzuki/items/5a4f680b10bb82501aa3
